// Generated by CoffeeScript 1.4.0

app.controller('NavController', function($scope, userService) {
  $scope.userService = userService;
  $scope.$watch('userService.get_user()', function(newValue, oldValue) {
    return $scope.user = newValue;
  });
  return $scope.has_signed_up = function() {
    if (userService.is_signed_in() && !userService.is_guest()) {
      return true;
    }
    return false;
  };
});
