// Generated by CoffeeScript 1.4.0

app.controller('ProductsController', function(productsService, $scope, $state) {
  return productsService.get_products().then(function(data) {
    return $scope.products = data.products;
  });
});
