// Generated by CoffeeScript 1.4.0

app.controller('SigninController', function(userService, $scope, $state) {
  $scope.signin_form = {
    is_loading: false,
    is_auth_error: false
  };
  return $scope.signin = function(form) {
    var promise;
    $scope.signin_form.is_loading = true;
    $scope.signin_form.is_auth_error = false;
    promise = userService.signin($scope.email_address, $scope.password);
    promise.then(function() {
      return $state.go('base.landing');
    }, function(error) {
      if (error.status === 401) {
        return $scope.signin_form.is_auth_error = true;
      }
    });
    return promise["finally"](function(data) {
      return $scope.signin_form.is_loading = false;
    });
  };
});
