// Generated by CoffeeScript 1.4.0

app.controller('SignoutController', function(userService, $scope, $state) {
  return $scope.signout = function() {
    return userService.signout().then(function() {
      return $state.go('base.landing');
    }, function(error) {});
  };
});
