// Generated by CoffeeScript 1.4.0
var app;

app = angular.module('app', ['ui.router', 'restangular', 'LocalStorageModule', 'cgNotify']);

app.config(function($stateProvider, $urlRouterProvider) {
  $urlRouterProvider.otherwise('/');
  return $stateProvider.state('base', {
    abstract: true,
    url: '/',
    templateUrl: 'partials/base.html',
    controller: 'BaseController',
    auth_required: true
  }).state('base.landing', {
    url: '',
    templateUrl: 'partials/base.landing.html',
    auth_required: true
  }).state('base.signin', {
    url: 'signin',
    templateUrl: 'partials/base.signin.html',
    controller: 'SigninController',
    auth_required: false
  });
});

app.config(function(RestangularProvider, API_END_POINT) {
  return RestangularProvider.setBaseUrl(API_END_POINT);
});

app.config(function(localStorageServiceProvider) {
  return localStorageServiceProvider.setPrefix('festeasy').setStorageType('sessionStorage').setNotify(true, true);
});

app.run(function($rootScope, $state, $stateParams) {
  $rootScope.$state = $state;
  return $rootScope.$stateParams = $stateParams;
});

app.run(function(notify) {
  return notify.config({
    duration: 3000,
    position: 'center',
    templateUrl: 'templates/notification.html'
  });
});

app.run(function(Restangular, $state, userService) {
  return Restangular.setErrorInterceptor(function(error) {
    if (error.status === 401 && $state.current.name !== 'base.signin') {
      return userService.signout();
    }
  });
});

app.run(function(userService) {
  userService.load_session_from_cookie();
  if (userService.is_signed_in()) {
    return userService.get();
  }
});
