"""add product category unique contraint

Revision ID: 2374be50097b
Revises: a3bc05d1c4f9
Create Date: 2016-09-07 22:02:45.800421

"""

# revision identifiers, used by Alembic.
revision = '2374be50097b'
down_revision = 'a3bc05d1c4f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'product_category', ['product_id', 'category_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_category', type_='unique')
    ### end Alembic commands ###
