"""add festival image

Revision ID: a3bc05d1c4f9
Revises: f4ab7eacb3b0
Create Date: 2016-08-23 21:04:51.205210

"""

# revision identifiers, used by Alembic.
revision = 'a3bc05d1c4f9'
down_revision = 'f4ab7eacb3b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('festival', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'festival', 'image', ['image_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'festival', type_='foreignkey')
    op.drop_column('festival', 'image_id')
    ### end Alembic commands ###
