"""use one-to-one for payments on payu_transaction

Revision ID: e88000ef95a4
Revises: 06d480557278
Create Date: 2016-08-21 17:38:02.152992

"""

# revision identifiers, used by Alembic.
revision = 'e88000ef95a4'
down_revision = '06d480557278'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pay_u_transaction', ['payment_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pay_u_transaction', type_='unique')
    ### end Alembic commands ###
