"""add shipping address to order

Revision ID: f4ab7eacb3b0
Revises: e88000ef95a4
Create Date: 2016-08-22 22:42:07.213315

"""

# revision identifiers, used by Alembic.
revision = 'f4ab7eacb3b0'
down_revision = 'e88000ef95a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('shipping_address', sa.String()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'shipping_address')
    ### end Alembic commands ###
