// Generated by CoffeeScript 1.4.0

app.factory('productsService', [
  'Restangular', '$q', function(Restangular, $q) {
    var fac, get_products,
      _this = this;
    fac = {};
    get_products = function() {
      var deferred;
      deferred = $q.defer();
      Restangular.one('products').get().then(function(data) {
        return deferred.resolve(data);
      }, function(error) {
        return deferred.reject(error);
      });
      return deferred.promise;
    };
    fac.get_products = get_products;
    return fac;
  }
]);
