// Generated by CoffeeScript 1.4.0

app.directive('myGreetingNavbarText', [
  function() {
    return {
      restrict: 'AE',
      templateUrl: 'templates/my-greeting-navbar-text.html',
      scope: {
        firstName: '='
      }
    };
  }
]);

app.directive('mySignInNavButton', [
  'userService', '$state', function(userService, $state) {
    return {
      restrict: 'AE',
      templateUrl: 'templates/my-sign-in-nav-button.html'
    };
  }
]);
